---
- name: Add yum repository for Kubernetes stable
  yum_repository:
    name: kubernetes
    description: Kubernetes - $basearch
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    gpgcheck: "yes"
    enabled: "yes"
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
    exclude: kubelet kubeadm kubectl
    state: present
    reposdir: /etc/yum.repos.d

- name: Install Kubernetes
  yum:
    name: "{{ packages }}"
    state: present
    disable_excludes: kubernetes
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl
      - iproute-tc
  notify:
    - kubelet status

- name: Configure /tmp/kubeadmin-init.conf
  copy:
    dest: "/tmp/kubeadmin-init.conf"
    content: |
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      cgroupDriver: systemd

- name: Configure /etc/sysconfig/kubelet
  copy:
    dest: "/etc/sysconfig/kubelet"
    content: |
      KUBELET_EXTRA_ARGS=--cgroup-driver=systemd

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: "yes"
    state: started
    enabled: "yes"
