---
- name: Install haproxy
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: "yes"
  vars:
    packages:
      - haproxy
      - libselinux-python
      - libsemanage-python

- name: Copy in haproxy config
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_haproxy

- name: Set haproxy_connect_any flag on and keep it persistent across reboots
  seboolean:
    name: haproxy_connect_any
    state: "yes"
    persistent: "yes"

- name: Start service haproxy, if not started
  service:
    name: haproxy
    daemon_reload: "yes"
    state: started
    enabled: "yes"
