---
- name: Install dnsmasq
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: "yes"
  vars:
    packages:
      - dnsmasq
        #- NetworkManager-glib

- name: Copy in dnsmasq config
  copy:
    src: kubernetes.conf
    dest: /etc/dnsmasq.d/kubernetes.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart_dnsmasq

- name: Start service dnsmasq, if not started
  service:
    name: dnsmasq
    daemon_reload: "yes"
    state: started
    enabled: "yes"

- name: Use dnsmasq before falling back to dhcp provided dns
  copy:
    dest: "/etc/dhcp/dhclient.conf"
    content: |
      supersede domain-search "kube1.vm.test";
      prepend domain-name-servers 127.0.0.1;
  notify:
    - restart_NetworkManager

- name: Change NM to use dhclient
  copy:
    src: nm-dhclient.conf
    dest: /etc/NetworkManager/conf.d/nm-dhclient.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart_NetworkManager

- name: Restart NetworkManager if 127.0.0.1 not in nameservers
  service:
    name: NetworkManager
    state: restarted
  when: '"127.0.0.1" not in ansible_dns.nameservers'
