---
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker

- name: Install required packages.
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: "yes"
  vars:
    packages:
      - device-mapper-persistent-data
      - lvm2
      - yum-utils

- name: Add yum repository for Docker stable
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable/
    gpgcheck: "yes"
    gpgkey: https://download.docker.com/linux/centos/gpg
    state: present
    enabled: "no"

- name: Install docker
  yum:
    name: "{{ packages }}"
    state: present
    enablerepo: docker-ce-stable
  vars:
    packages:
      - containerd.io-1.2.13
      - docker-ce-19.03.8
      - docker-ce-cli-19.03.8
  notify:
    - docker status


- name: Create docker etc directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy in docker daemon settings
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'


- name: Create docker systemd overrides directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Start service docker, if not started
  service:
    name: docker
    daemon_reload: "yes"
    state: started
    enabled: "yes"

- name: Add vagrant user to docker group
  user:
    name: vagrant
    group: docker
